Repository pharmaziegasse/charm-backend, pull requests merged in 2019-08, with the labels that each got.

#2 Add basic templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  PULL_REQUEST_TEMPLATE
Labels: enhancement

#4 Initial Wagtail Setup
  .gitignore
  .vscode/settings.json
  Dockerfile
  charm/__init__.py
  charm/home/__init__.py
  charm/home/migrations/0001_initial.py
  charm/home/migrations/0002_create_homepage.py
  charm/home/migrations/0003_auto_20190809_1419.py
  charm/home/migrations/__init__.py
  charm/home/models.py
  charm/home/static/css/welcome_page.css
  charm/home/templates/home/charm_page.html
  charm/settings/__init__.py
  charm/settings/base.py
  charm/settings/dev.py
  charm/settings/production.py
  charm/static/css/charm.css
  charm/static/js/charm.js
  charm/templates/404.html
  charm/templates/500.html
  charm/templates/base.html
  charm/urls.py
  charm/wsgi.py
  manage.py
  requirements.txt
Labels: enhancement

#6 Adjust base settings and add production settings
  charm/home/migrations/0004_auto_20190819_1228.py
  charm/settings/base.py
  charm/settings/production.py
Labels: enhancement

#9 Add GraphQL API
  charm/api/__init__.py
  charm/api/actions.py
  charm/api/apps.py
  charm/api/permissions.py
  charm/api/registry.py
  charm/api/relay.py
  charm/api/schema.py
  charm/api/settings.py
  charm/api/types/__init__.py
  charm/api/types/auth.py
  charm/api/types/converters.py
  charm/api/types/core.py
  charm/api/types/documents.py
  charm/api/types/forms.py
  charm/api/types/images.py
  charm/api/types/menus.py
  charm/api/types/settings.py
  charm/api/types/snippets.py
  charm/api/types/streamfield.py
  charm/settings/__init__.py
  charm/settings/base.py
  charm/urls.py
Labels: enhancement

#12 Add custom User model
  charm/settings/base.py
  charm/user/apps.py
  charm/user/migrations/0001_initial.py
  charm/user/migrations/0002_auto_20190819_2007.py
  charm/user/migrations/0003_auto_20190819_2100.py
  charm/user/migrations/__init__.py
  charm/user/models.py
  charm/user/schema.py
  charm/user/wagtail_hooks.py
Labels: enhancement

#19 Add anamnese app
  charm/anamnese/apps.py
  charm/anamnese/migrations/0001_initial.py
  charm/anamnese/migrations/__init__.py
  charm/anamnese/models.py
  charm/anamnese/wagtail_hooks.py
  charm/settings/base.py
  charm/user/models.py
  charm/user/wagtail_hooks.py
Labels: enhancement

#20 Add beautyreport app
  charm/beautyreport/apps.py
  charm/beautyreport/migrations/0001_initial.py
  charm/beautyreport/migrations/__init__.py
  charm/beautyreport/models.py
  charm/beautyreport/schema.py
  charm/beautyreport/wagtail_hooks.py
  charm/settings/base.py
Labels: enhancement

#23 Add anamnese and beautyreport formpage
  charm/anamnese/migrations/0002_auto_20190821_1050.py
  charm/anamnese/migrations/0003_anformpage_user_panel.py
  charm/anamnese/migrations/0004_auto_20190821_1208.py
  charm/anamnese/migrations/0005_remove_anformpage_uid.py
  charm/anamnese/migrations/0006_anformpage_uid.py
  charm/anamnese/models.py
  charm/api/types/auth.py
  charm/api/types/core.py
  charm/beautyreport/migrations/0002_auto_20190821_1304.py
  charm/beautyreport/models.py
  charm/settings/base.py
  charm/user/models.py
Labels: enhancement

#24 Add anamnese GraphQL queries
  charm/anamnese/models.py
  charm/anamnese/schema.py
  charm/api/schema.py
  charm/user/models.py
Labels: enhancement

#25 Add beautyreport GraphQL queries
  charm/api/schema.py
  charm/beautyreport/models.py
  charm/beautyreport/schema.py
Labels: enhancement

#27 Add docker configuration
  .dockerignore
  Dockerfile
  docker-compose.yml
  docker-entrypoint.sh
Labels: enhancement

#28 Add reports templatepage
  charm/reports/apps.py
  charm/reports/migrations/0001_initial.py
  charm/reports/migrations/0002_reportspage_paragraphs.py
  charm/reports/migrations/0003_auto_20190821_1745.py
  charm/reports/migrations/__init__.py
  charm/reports/models.py
  charm/reports/static/css/font.css
  charm/reports/wagtail_hooks.py
  charm/settings/base.py
Labels: enhancement

#31 Add requirements and CORS configuration
  charm/settings/base.py
  docker-entrypoint.sh
  requirements.txt
  requirements/base.txt
  requirements/production.txt
Labels: enhancement

#33 Add WSGI Production file
  charm/wsgi_production.py
Labels: bug

#36 Add User schema
  charm/api/schema.py
  charm/user/models.py
  charm/user/schema.py
Labels: bug, enhancement

#38 Rework beautyreport template page
  charm/reports/migrations/0004_auto_20190823_1057.py
  charm/reports/models.py
Labels: enhancement

#41 Add userByName Query
  charm/user/schema.py
Labels: enhancement

#44 Change User Identificator
  charm/user/models.py
Labels: enhancement

#46 Add Customer and Coach Proxy Models / Fix some things
  charm/anamnese/migrations/0007_auto_20190828_1415.py
  charm/anamnese/models.py
  charm/beautyreport/migrations/0003_auto_20190828_1415.py
  charm/coach/apps.py
  charm/coach/migrations/0001_initial.py
  charm/coach/migrations/__init__.py
  charm/coach/models.py
  charm/coach/schema.py
  charm/coach/wagtail_hooks.py
  charm/customer/apps.py
  charm/customer/migrations/0001_initial.py
  charm/customer/migrations/__init__.py
  charm/customer/models.py
  charm/customer/schema.py
  charm/customer/wagtail_hooks.py
  charm/reports/migrations/0005_auto_20190828_1415.py
  charm/settings/base.py
  charm/user/migrations/0004_auto_20190828_1415.py
  charm/user/models.py
  charm/user/schema.py
Labels: bug, enhancement

#49 Add GraphQL support for Coach and Customer Objects
  charm/api/schema.py
  charm/coach/schema.py
  charm/customer/schema.py
  charm/user/migrations/0005_auto_20190829_1148.py
  charm/user/models.py
Labels: enhancement

#51 Rework phone login solution / Add queries to get a username
  charm/coach/wagtail_hooks.py
  charm/user/migrations/0006_auto_20190829_1912.py
  charm/user/models.py
  charm/user/schema.py
Labels: enhancement

#56 Fix coach graphene permissions
  charm/anamnese/schema.py
  charm/beautyreport/schema.py
  charm/coach/schema.py
  charm/customer/schema.py
  charm/user/migrations/0007_auto_20190830_1246.py
  charm/user/models.py
  charm/user/schema.py
Labels: bug

#58 Fix error when querying all Coaches or Customers
  charm/coach/schema.py
  charm/customer/schema.py
Labels: bug

#59 Add extra Type for querying Coaches and Customers
  charm/coach/schema.py
  charm/customer/schema.py
Labels: bug
